"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import AuthProvider from "./Provider";
import Header from "@/components/header/Header";
import { usePathname } from "next/navigation";
import MobileMenu from "@/components/component/mobileMenu/MobileMenu";

const font = Poppins({ 
  subsets: ["latin"],
  weight: ["100","200","300","500","600","700","800"],
});

// Define a function to generate metadata
const generateMetadata = (pathname: string): Metadata => {
  if (pathname.startsWith("/ilan/")) {
    return {
      title: "Custom Title for Ilan Page",
      description: "Custom description for Ilan Page",
    };
  } else {
    return {
      title: "Create Next App",
      description: "Generated by create next app",
    };
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const metadata = generateMetadata(pathname); // Use the generated metadata

  return (
    <html lang="en">
      <AuthProvider>
        <head>
          <title>{metadata.title}</title>
          <meta name="description" content={metadata.description} />
        </head>
        <body className={font.className}>
          {pathname === "/login" || pathname === "/register" || pathname === "/ilan" ? null : <Header />}

          {children}
          {pathname === "/login" || pathname === "/register" || pathname === "/ilan" || pathname.startsWith("/ilan/") ? null : <MobileMenu />}
        </body>
      </AuthProvider>
    </html>
  );
}

